<?php

declare(strict_types=1);

use App\Http\Controllers\AuthController;
use App\Http\Controllers\AuditAdminController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\MenuAdminController;
use App\Http\Controllers\OperationsController;
use App\Http\Controllers\PlatformSettingsController;
use App\Http\Controllers\RestaurantOnboardingController;
use App\Http\Controllers\RestaurantAdminController;
use App\Http\Controllers\TenantAccessController;
use App\Http\Controllers\TenantPortalController;
use App\Http\Controllers\UserAdminController;
use App\Middleware\AuthMiddleware;
use App\Middleware\KitchenAccessMiddleware;
use App\Middleware\OwnerOrManagerMiddleware;
use App\Middleware\OwnerAreaMiddleware;
use App\Middleware\ReportsAccessMiddleware;
use App\Middleware\SalesAccessMiddleware;
use App\Middleware\StockAccessMiddleware;
use App\Middleware\SuperAdminMiddleware;

$router->get('/', [RestaurantOnboardingController::class, 'home']);
$router->get('/health', [DashboardController::class, 'health']);
$router->get('/login', [AuthController::class, 'showLogin']);
$router->post('/login', [AuthController::class, 'login']);
$router->get('/creer-mon-restaurant', [RestaurantOnboardingController::class, 'showRegistration']);
$router->post('/creer-mon-restaurant', [RestaurantOnboardingController::class, 'register']);
$router->get('/logout', [AuthController::class, 'logout'], [AuthMiddleware::class]);
$router->get('/super-admin', [DashboardController::class, 'superAdmin'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/reset/preview', [DashboardController::class, 'previewOperationalReset'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/reset/execute', [DashboardController::class, 'executeOperationalReset'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/stock-reset/preview', [DashboardController::class, 'previewStockReset'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/stock-reset/execute', [DashboardController::class, 'executeStockReset'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/operations/lookup', [DashboardController::class, 'superAdminOperationLookup'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/operations/force', [DashboardController::class, 'superAdminOperationForce'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->get('/super-admin/restaurants', [RestaurantAdminController::class, 'index'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/restaurants', [RestaurantAdminController::class, 'store'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->get('/super-admin/restaurants/{id}', [RestaurantAdminController::class, 'show'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/restaurants/{id}/update', [RestaurantAdminController::class, 'update'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/restaurants/{id}/branding', [RestaurantAdminController::class, 'updateBranding'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/restaurants/{id}/settings', [RestaurantAdminController::class, 'updateSettings'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/restaurants/{id}/status', [RestaurantAdminController::class, 'changeStatus'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/restaurants/{id}/subscription/activate', [RestaurantAdminController::class, 'activateSubscription'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->get('/super-admin/users', [UserAdminController::class, 'index'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/users', [UserAdminController::class, 'store'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/users/{id}/update', [UserAdminController::class, 'update'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/users/{id}/status', [UserAdminController::class, 'changeStatus'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->get('/super-admin/audit', [AuditAdminController::class, 'index'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->get('/super-admin/settings', [PlatformSettingsController::class, 'index'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/settings', [PlatformSettingsController::class, 'update'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->get('/super-admin/menu', [MenuAdminController::class, 'superAdminIndex'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/menu/categories', [MenuAdminController::class, 'storeCategory'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/menu/categories/{id}/update', [MenuAdminController::class, 'updateCategory'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/menu/items', [MenuAdminController::class, 'storeItem'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/menu/items/{id}/update', [MenuAdminController::class, 'updateItem'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->post('/super-admin/menu/items/{id}/status', [MenuAdminController::class, 'markStatus'], [AuthMiddleware::class, SuperAdminMiddleware::class]);
$router->get('/owner', [DashboardController::class, 'owner'], [AuthMiddleware::class, OwnerAreaMiddleware::class]);
$router->post('/owner/subscription/pay', [RestaurantAdminController::class, 'declarePayment'], [AuthMiddleware::class, OwnerAreaMiddleware::class]);
$router->post('/owner/settings/currency', [RestaurantAdminController::class, 'updateOwnerCurrency'], [AuthMiddleware::class, OwnerOrManagerMiddleware::class]);
$router->get('/owner/menu', [MenuAdminController::class, 'ownerIndex'], [AuthMiddleware::class, OwnerAreaMiddleware::class]);
$router->post('/owner/menu/categories', [MenuAdminController::class, 'storeOwnerCategory'], [AuthMiddleware::class, OwnerOrManagerMiddleware::class]);
$router->post('/owner/menu/items', [MenuAdminController::class, 'storeOwnerItem'], [AuthMiddleware::class, OwnerOrManagerMiddleware::class]);
$router->post('/owner/menu/items/{id}/update', [MenuAdminController::class, 'updateOwnerItem'], [AuthMiddleware::class, OwnerOrManagerMiddleware::class]);
$router->get('/owner/access', [TenantAccessController::class, 'index'], [AuthMiddleware::class, OwnerAreaMiddleware::class]);
$router->get('/owner/access/users/{id}', [TenantAccessController::class, 'showUserHistory'], [AuthMiddleware::class, OwnerAreaMiddleware::class]);
$router->post('/owner/access/roles', [TenantAccessController::class, 'storeRole'], [AuthMiddleware::class, OwnerAreaMiddleware::class]);
$router->post('/owner/access/roles/{id}/permissions', [TenantAccessController::class, 'updateRolePermissions'], [AuthMiddleware::class, OwnerAreaMiddleware::class]);
$router->post('/owner/access/roles/{id}/status', [TenantAccessController::class, 'changeRoleStatus'], [AuthMiddleware::class, OwnerAreaMiddleware::class]);
$router->post('/owner/access/users/{id}/role', [TenantAccessController::class, 'assignUserRole'], [AuthMiddleware::class, OwnerAreaMiddleware::class]);
$router->post('/owner/menu/items/{id}/status', [MenuAdminController::class, 'markStatus'], [AuthMiddleware::class, OwnerOrManagerMiddleware::class]);
$router->get('/stock', [OperationsController::class, 'stock'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/items', [OperationsController::class, 'createStockItem'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/items/{id}/update', [OperationsController::class, 'updateStockItem'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/items/{id}/archive', [OperationsController::class, 'archiveStockItem'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/entries', [OperationsController::class, 'addStockEntry'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/mouvements-libres', [OperationsController::class, 'recordFreeStockMovement'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/sorties-cuisine', [OperationsController::class, 'sendToKitchen'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/retours', [OperationsController::class, 'validateReturnStock'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/retours-endommages', [OperationsController::class, 'signalDamagedStockReturn'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/pertes', [OperationsController::class, 'createLoss'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/movements/{id}/correction-request', [OperationsController::class, 'requestStockMovementCorrection'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/corrections/sensitive', [OperationsController::class, 'requestSensitiveCorrection'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/demandes-cuisine/{id}/reponse', [OperationsController::class, 'respondKitchenStockRequest'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/demandes-cuisine/{id}/decliner', [OperationsController::class, 'declineKitchenStockRequest'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->post('/stock/demandes-cuisine/{id}/incident', [OperationsController::class, 'signalKitchenStockIncident'], [AuthMiddleware::class, StockAccessMiddleware::class]);
$router->get('/cuisine', [OperationsController::class, 'kitchen'], [AuthMiddleware::class, KitchenAccessMiddleware::class]);
$router->post('/cuisine/productions', [OperationsController::class, 'createKitchenProduction'], [AuthMiddleware::class, KitchenAccessMiddleware::class]);
$router->post('/cuisine/retours', [OperationsController::class, 'validateKitchenReturn'], [AuthMiddleware::class, KitchenAccessMiddleware::class]);
$router->post('/cuisine/incidents', [OperationsController::class, 'signalKitchenIncident'], [AuthMiddleware::class, KitchenAccessMiddleware::class]);
$router->post('/cuisine/demandes-stock', [OperationsController::class, 'requestKitchenStock'], [AuthMiddleware::class, KitchenAccessMiddleware::class]);
$router->post('/cuisine/demandes-stock/{id}/reception', [OperationsController::class, 'confirmKitchenStockReceipt'], [AuthMiddleware::class, KitchenAccessMiddleware::class]);
$router->post('/cuisine/demandes-stock/{id}/annuler', [OperationsController::class, 'cancelKitchenStockRequest'], [AuthMiddleware::class, KitchenAccessMiddleware::class]);
$router->post('/cuisine/demandes-serveur/{id}/decliner', [OperationsController::class, 'declineServerRequest'], [AuthMiddleware::class, KitchenAccessMiddleware::class]);
$router->post('/cuisine/demandes-serveur/{id}/fourni', [OperationsController::class, 'fulfillServerRequestItem'], [AuthMiddleware::class, KitchenAccessMiddleware::class]);
$router->get('/ventes', [OperationsController::class, 'sales'], [AuthMiddleware::class, SalesAccessMiddleware::class]);
$router->get('/ventes/factures/{id}', [OperationsController::class, 'printSaleReceipt'], [AuthMiddleware::class, SalesAccessMiddleware::class]);
$router->post('/ventes', [OperationsController::class, 'createSale'], [AuthMiddleware::class, SalesAccessMiddleware::class]);
$router->post('/ventes/demandes', [OperationsController::class, 'createServerRequest'], [AuthMiddleware::class, SalesAccessMiddleware::class]);
$router->post('/ventes/demandes/{id}/reception', [OperationsController::class, 'confirmServerRequestReceipt'], [AuthMiddleware::class, SalesAccessMiddleware::class]);
$router->post('/ventes/demandes/{id}/annuler', [OperationsController::class, 'cancelServerRequest'], [AuthMiddleware::class, SalesAccessMiddleware::class]);
$router->post('/ventes/demandes/{id}/cloture', [OperationsController::class, 'closeServerRequest'], [AuthMiddleware::class, SalesAccessMiddleware::class]);
$router->post('/ventes/incidents', [OperationsController::class, 'signalSaleIncident'], [AuthMiddleware::class, SalesAccessMiddleware::class]);
$router->post('/operations/cases/{id}/decision', [OperationsController::class, 'decideCase'], [AuthMiddleware::class]);
$router->post('/ventes/pertes-argent', [OperationsController::class, 'createCashLoss'], [AuthMiddleware::class, SalesAccessMiddleware::class]);
$router->get('/rapport', [OperationsController::class, 'report'], [AuthMiddleware::class, ReportsAccessMiddleware::class]);
$router->get('/caisse', [OperationsController::class, 'cash'], [AuthMiddleware::class]);
$router->post('/caisse/remises-serveur', [OperationsController::class, 'remitServerCash'], [AuthMiddleware::class]);
$router->post('/caisse/transferts/{id}/reception-caisse', [OperationsController::class, 'receiveCashAtCashier'], [AuthMiddleware::class]);
$router->post('/caisse/transferts/{id}/rejet-remise', [OperationsController::class, 'rejectSaleRemittanceAtCashier'], [AuthMiddleware::class]);
$router->post('/caisse/transferts/{id}/soumission-gerant', [OperationsController::class, 'submitSaleRemittanceToManagerFromCashier'], [AuthMiddleware::class]);
$router->post('/caisse/mouvements', [OperationsController::class, 'createCashMovement'], [AuthMiddleware::class]);
$router->post('/caisse/remises-gerant', [OperationsController::class, 'transferCashToManager'], [AuthMiddleware::class]);
$router->post('/caisse/transferts/{id}/reception-gerant', [OperationsController::class, 'receiveCashAtManager'], [AuthMiddleware::class]);
$router->post('/caisse/remises-proprietaire', [OperationsController::class, 'transferCashToOwner'], [AuthMiddleware::class]);
$router->post('/caisse/transferts/{id}/reception-proprietaire', [OperationsController::class, 'receiveCashAtOwner'], [AuthMiddleware::class]);
$router->post('/owner/correction-requests/{id}/decision', [OperationsController::class, 'decideCorrectionRequest'], [AuthMiddleware::class, OwnerOrManagerMiddleware::class]);
$router->post('/owner/caisse/remises-vente/{id}/decision', [OperationsController::class, 'decideManagerSaleRemittance'], [AuthMiddleware::class, OwnerOrManagerMiddleware::class]);
$router->get('/portal/register', [TenantPortalController::class, 'showRegistration']);
$router->post('/portal/register', [TenantPortalController::class, 'register']);
$router->get('/portal/{slug}/register', [TenantPortalController::class, 'showRegistration']);
$router->post('/portal/{slug}/register', [TenantPortalController::class, 'register']);
$router->get('/portal/{slug}', [TenantPortalController::class, 'show']);
